// Copyright 2026 The MediaPipe Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.mediapipe.tasks.vision.orientedobjectdetector;

import com.google.auto.value.AutoValue;
import com.google.mediapipe.tasks.components.containers.OrientedDetection;
import com.google.mediapipe.tasks.core.TaskResult;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** Represents the oriented detection results generated by {@link OrientedObjectDetector}. */
@AutoValue
public abstract class OrientedObjectDetectorResult implements TaskResult {
  public static OrientedObjectDetectorResult create(
      List<com.google.mediapipe.formats.proto.OrientedDetectionProto.OrientedDetection>
          detectionList,
      int imageWidth,
      int imageHeight,
      long timestampMs) {
    List<OrientedDetection> detections = new ArrayList<>();
    for (com.google.mediapipe.formats.proto.OrientedDetectionProto.OrientedDetection
        detectionProto : detectionList) {
      detections.add(OrientedDetection.createFromProto(detectionProto, imageWidth, imageHeight));
    }
    return new AutoValue_OrientedObjectDetectorResult(
        timestampMs, Collections.unmodifiableList(detections));
  }

  @Override
  public abstract long timestampMs();

  public abstract List<OrientedDetection> detections();
}
